name = "newsnow"
main = "dist/output/public/_worker.js/index.mjs"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-16"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsql"
database_id = "a0f01c88-4323-4c20-9a9f-cbfb3546bca0"
